version: '3.8'

services:
  proxy:
    container_name: mortgage-calculator-proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - mortgage-calculator-network
    restart: unless-stopped

  frontend:
    container_name: mortgage-calculator-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - REACT_APP_API_URL=http://localhost/api
      - PORT=3000
      # UI settings
      - REACT_APP_THEME_PRIMARY_COLOR=#2563EB
      - REACT_APP_THEME_SECONDARY_COLOR=#10B981
      - GENERATE_SOURCEMAP=false
    mem_limit: 2g
    depends_on:
      - backend
    networks:
      - mortgage-calculator-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  backend:
    container_name: mortgage-calculator-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://db:27017/mortgage-calculator
      - PORT=3010
      # Performance settings
      - MAX_PDF_SIZE=10485760 # 10MB in bytes
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mortgage-calculator-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3010/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  db:
    container_name: mortgage-calculator-db
    image: mongo:latest
    volumes:
      - mortgage-calculator-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mortgage-calculator-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  mortgage-calculator-network:
    driver: bridge

volumes:
  mortgage-calculator-data:
    driver: local 