version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
    networks:
      - db-network
    restart: unless-stopped

networks:
  db-network:
    driver: bridge 