version: '3.8'

services:
  proxy:
    container_name: mortgage-calculator-proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - mortgage-calculator-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    container_name: mortgage-calculator-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
      args:
        - REACT_APP_API_URL=/api
    networks:
      - mortgage-calculator-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    container_name: mortgage-calculator-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://db:27017/mortgage-calculator
      - MAX_PDF_SIZE=10485760 # 10MB in bytes
    depends_on:
      - db
    networks:
      - mortgage-calculator-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3010/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    container_name: mortgage-calculator-db
    image: mongo:latest
    volumes:
      - mortgage-calculator-data:/data/db
    networks:
      - mortgage-calculator-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mortgage-calculator-network:
    driver: bridge

volumes:
  mortgage-calculator-data:
    driver: local 