version: '3.8'

services:
  db:
    container_name: mortgage-calculator-db
    image: mongo:4.4
    ports:
      - "27018:27017"
    networks:
      - mortgage-calculator-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  mortgage-calculator-network:
    driver: bridge 