services:
  # Frontend web service
  - type: web
    name: mortgage-calculator-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: mortgage-calculator-backend
          type: web
          property: url
        sync: false
      - key: REACT_APP_THEME_PRIMARY_COLOR
        value: "#2563EB"
      - key: REACT_APP_THEME_SECONDARY_COLOR
        value: "#10B981"

  # Backend API service
  - type: web
    name: mortgage-calculator-backend
    env: node
    plan: starter
    runtime: node
    nodeVersion: 20.x
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MAX_PDF_SIZE
        value: 10485760
      - key: MONGODB_URI
        fromDatabase:
          name: mortgage-calculator-db
          property: connectionString

databases:
  - name: mortgage-calculator-db
    databaseName: mortgage-calculator
    plan: free 