services:
  # Frontend web service
  - type: web
    name: mortgage-calculator-frontend
    env: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/build
    pullRequestPreviewsEnabled: false
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: mortgage-calculator-backend
          type: web
          property: url
        sync: false
      - key: REACT_APP_THEME_PRIMARY_COLOR
        value: "#2563EB"
      - key: REACT_APP_THEME_SECONDARY_COLOR
        value: "#10B981"

  # Backend API service
  - type: web
    name: mortgage-calculator-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm run start:prod
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MAX_PDF_SIZE
        value: 10485760
      - key: MONGODB_URI
        sync: false
      # Add debug options for easier troubleshooting
      - key: DEBUG
        value: "true"
      # Mongoose connection retry options
      - key: MONGOOSE_DEBUG
        value: "true"
      # Other MongoDB related configs
      - key: TZ
        value: "UTC"

databases:
  - name: mortgage-calculator-db
    databaseName: mortgage-calculator
    plan: free 