services:
  # Monolithic web service (frontend + backend)
  - type: web
    name: mortgage-calculator
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    startCommand: node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MAX_PDF_SIZE
        value: 10485760
      - key: MONGODB_URI
        fromDatabase:
          name: mortgage-calculator-db
          property: connectionString
          append: "?authSource=admin&retryWrites=true&w=majority"
      - key: REACT_APP_THEME_PRIMARY_COLOR
        value: "#2563EB"
      - key: REACT_APP_THEME_SECONDARY_COLOR
        value: "#10B981"

databases:
  - name: mortgage-calculator-db
    databaseName: mortgage-calculator
    plan: free 